### ISSUE TITLE
[Error] Please open an editor to use this function

### ISSUE THREAD

**Issue by cristian-recoseanu** [qcz/vscode-text-power-tools#1]
No matter what function I try and call upon I keep getting the "Please open an editor to use this function" error in VS Code.

Text Power Tools version 1.1.0
VSCode version 1.26.1

**Comment by cristian-recoseanu** [comment]
Ok the error was misleading.

It seems it can only handle .txt files whereas I was trying to manipulate a .log file.

Is there any practical reason why it couldn't deal with other text file extensions?

I can see this being really useful for running queries on log files.

Thanks!

**Comment by cristian-recoseanu** [comment]
Another update to this.

It also seems that if the *.txt file is quite large I get the same "Please open an editor to use this function" error but works fine for small files.

**Comment by qcz** [comment]
I've looked into the problem, and unfortunately it looks like that extensions cannot see large files by design (see Microsoft/vscode#3147). The actual limit seems to be 50Mb on my machine for both stable and insiders versions.

I'll try to improve the error message at least, and later try to find some other way to perform these operations.

**Comment by cristian-recoseanu** [comment]
Ahh that's a shame.
This would have been tremendous for log file querying.

The file I was trying this on was just above the limit at 23Mb.

Thanks for the comments and good luck with everything!

**Comment by qcz** [comment]
I've updated the message displayed by the extension when it does not see an active editor (nothing is open or the file is too big).

If Microsoft/vscode#31078 will be implemented, you will be able to configure the size limit of the files visible by extensions, so I suggest that you should upvote that issue to signal the need for that feature.
