### ISSUE TITLE
I can't find this in the VSCode extensions within the editor/IDE

### ISSUE THREAD

**Issue by OdinsHat** [qcz/vscode-text-power-tools#10]
I have tried finding this extension in VSCode but can't. The only way I can find it is on the site. Is there something you can do with the published extension to make it more easily discoverable by users searching within the app?

I think this extension deserves more installs and visibility. I shouldn't have to search on the VSCode extensions page to find it. If there's some way you can improve its visibility in the IDE/editor that would be great as this extension is **very** useful.

**Comment by qcz** [comment]
Thank you for the kind words!

How did you tried to search for it? What version of VS Code do you use and what is the language of the interface? I can find TPT on the first page using these keywords:
* text (5th)
* text utilities (3rd)
* grep (7th)
* filtering (2nd)
* filter text (4th)

Not so good, but still there:
* text tools (10th)
* base64 (12th)
* filter (21st)
* many other keywords, but they are waaay down

I actively try to optimize keywords so Text Power Tools can be found via various ways. Other than optimizing search keywords and the description and promoting the extension here and there (for example it is on [awesome-vscode](https://github.com/viatsko/awesome-vscode#text-power-tools)), I don't know what can I do to further improve the visibility of the extension. The algorithm driving the VS Code is not so deterministic unfortunately.

I am open to any suggestions which can improve the visibility of the extension.

**Comment by OdinsHat** [comment]
Sorry @qcz . It's entirely user error this time. I was using [Code - OSS](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code) on Arch Linux. Its the non-MS supported open source version of VSCode and it doesn't include some extensions. I did try asking if there's a way to get your plugin included but couldn't find an answer. Maybe its a licensing thing? Either way your extension is perfectly installable on the proper MS Visual Studio Code and Insider version from MS. Sorry for the bother and thanks for the great extension. :)

**Comment by OdinsHat** [comment]
@qcz you may be able to make sure it shows in the OSS version by publishing your extension on the global [Open VSX](https://open-vsx.org) site. It's a site for publishing extensions compatible with VSCode. I noticed yours isn't listed but if you published it on there you may find your extension show up on the Code - OSS edition of VSCode. That's only if you're interested in doing it. It's worth noting a lot of Linux distros only allow installation of the non-MS build of VSCode (aka. Code OSS). So you may get a slightly larger audience if you publish on there. I hope this is helpful.

**Comment by qcz** [comment]
@OdinsHat: Thanks for the tip. It is now available on Open VSX: https://open-vsx.org/extension/qcz/text-power-tools

**Comment by qcz** [comment]
I've tested it in VSCodium, and it works perfectly.

**Comment by OdinsHat** [comment]
That;'s great news @qcz ! It shows up on my Code OSS version on Arch Linux now too as well as the Code OSS version on Ubuntu. You can probably close it now. Thanks again and look forward to more installs! 🙂
