### ISSUE TITLE
Version sort

### ISSUE THREAD

**Issue by exploide** [qcz/vscode-text-power-tools#13]
Just discovered your extension, looks really useful! Thanks for that :)

I have the following usecase: I often write reports containing lists of IP addresses. When I paste such a list into my document, it is perfectly possible that the list is completely unsorted and might even contain duplicates.

Getting rid of duplicates is easy with the "Remove duplicated lines" option.

But sorting IP addresses looks more difficult on the first look. However, Unix `sort` has the `-V` options that does a version sort. E.g. sorting something like `1.10.3` and `1.12.1`. Luckily, this is the same logic needed for sorting IP addresses. So in the past, I just did `sort -uV` (to also apply uniq filtering) on my list.

I would like to propose the version sort functionality of `sort -V` for Text Power Tools. What do you think?

(As an alternative, I also thought if providing an arbitrary shell command filter would be useful, i.e. a text field where I can enter whatever command I want the text to be piped through. However, this might be out of scope of your extension?)

**Comment by qcz** [comment]
Great idea! I added it to my TODO list.

**Comment by qcz** [comment]
Hello @exploide!

I've published version 1.21.0 which contains commands for sorting IP addresses (and also using semver version rules, but that's not working with IP addresses).
Current limitation is that lines must contain IP addresses and nothing else. Please check whether it is fine for your use case.

**Comment by qcz** [comment]
Great! Closing the issue.
