### ISSUE TITLE
Cannot convert negative numbers to hexadecimal

### ISSUE THREAD

**Issue by iqapps** [qcz/vscode-text-power-tools#14]
Did expect that selecting something like "-126" could be converted to hex as something like 0xFFFFFF82, but no :-(

**Comment by qcz** [comment]
A simple hexadecimal converter should convert it to `-7E` (which TPT does not do currently, so it's a missing feature).

But what you would like is a hexadecimal converter using 16/32/64 bit arithmetic.

**Comment by qcz** [comment]
Converting decimal to hexadecimal using various arithmetic options are are available in the new 1.22.0 update.
