### ISSUE TITLE
Please add advanced sorting

### ISSUE THREAD

**Issue by alexolog** [qcz/vscode-text-power-tools#15]
Followup from #3 

TextFx had the option to sort lines in either case-sensitive or case-insensitive manner, as well as sorting byt text at a specified column.

VSCode built-in sort only supports case-sensitive sort at the first column.

**Comment by qcz** [comment]
How should sorting the text at a specified column work?
- Short by rest of the text starting at column X?
- What should happen with rows which are shorter than X characters?

**Comment by alexolog** [comment]
I am not sure how TextFX handles it but I would assume that they should be placed first given that the "value" at column X is null.

**Comment by qcz** [comment]
These sorting options (and more) are available in the new 1.22.0 update.

**Comment by alexolog** [comment]
Thank you!
