### ISSUE TITLE
Insert <any> number sequence starting at 0 actually starts at 1

### ISSUE THREAD

**Issue by FPtje** [qcz/vscode-text-power-tools#16]
## Summary

When using the option to insert a number sequence starting at a given number, and giving `0` as that given number, the sequence will actually start with 1. Negative numbers appear to work fine.

## Reproducing

- Have multiple selections
- Open command palette, select `Insert {decimal/hex/roman numeral} number sequence [with custom increment] starting at...`
- In the pop up window, enter `0`
- When `with custom increment is selected`, fill in any number
- Find that the inserted number sequence actually starts at `1`, giving the exact same result as when `1` would have been entered instead

This seems like a bug. Sequences starting at 0 are my second most common use case. I often find myself using a different extension to translate the sequence to subtract one off each element.

**Comment by qcz** [comment]
Fixed in 1.22.1.

**Comment by FPtje** [comment]
Wow, that's quick! Thanks a lot!
