### ISSUE TITLE
textPowerTools.removeBlankLines: Does not removes lines if they have white spaces

### ISSUE THREAD

**Issue by schittli** [qcz/vscode-text-power-tools#17]
Good evening

**thank you very much for sharing your great and very useful power tools!**

I have just tested the `textPowerTools.removeBlankLines` command and it works perfect if lines do not have any characters.
But if lines contain spaces or tabs, then they will not be deleted.

It would be very useful if:
- `removeBlankLines` would delete lines containing white spaces
- or to have a command like remove**Empty**Lines :-)

Thanks a lot, kind regards,
Thomas

**Comment by qcz** [comment]
Available in 1.25.0.

The existing remove blank lines commands were renamed to remove empty lines, and a proper remove blank lines command is added.
