### ISSUE TITLE
This function requires an active editor. If you have an open editor, the file may be too large. VS Code hides these files from extensions like *Text Power Tools*. Vote on this issue to make this limit lifted.

### ISSUE THREAD

**Issue by wa1one** [qcz/vscode-text-power-tools#19]
This function requires an active editor. If you have an open editor, the file may be too large. VS Code hides these files from extensions like *Text Power Tools*. Vote on this issue to make this limit lifted.

But file is not large.

**Comment by qcz** [comment]
Please provide more details about the error and how to reproduce it.

**Comment by qcz** [comment]
Closing this for now. Feel free to reopen it with additional information.
