### ISSUE TITLE
Activating extension 'qcz.text-power-tools' failed: Cannot find module 'uuid'.

### ISSUE THREAD

**Issue by tiansin** [qcz/vscode-text-power-tools#2]
Developer console output error after upgrading to the latest version.

Is it possible to integrate this plugin command to remove control characters into Text Power Tools?
https://marketplace.visualstudio.com/items?itemName=satokaz.vscode-bs-ctrlchar-remover

**Comment by qcz** [comment]
Thanks for the bug report! It is fixed in a35b2d3be26190df469e2a8be49b00b5e0d268eb published as 1.7.1 which is available now in the marketplace.

To your other question: yes, it is possible to integrate a function like that to Text Power Tools. I'll add it to one of the upcoming versions.
