### ISSUE TITLE
Convert from dash to Title

### ISSUE THREAD

**Issue by hukacode** [qcz/vscode-text-power-tools#20]
Hello,

Could you please consider this use case?
Input: type-checking-type-inference-and-restrictions
Expect: Type checking Type Inference And Restrictions

I used "Transform to Title Case" but the output is: Type-checking-type-inference-and-restrictions

**Comment by qcz** [comment]
I've added a new __Change case to title case__ command in the now available 1.28.0 version which works as you requested.

**Comment by hukacode** [comment]
Thank you so much.
