### ISSUE TITLE
Search for multiple patterns in a file

### ISSUE THREAD

**Issue by BrendanSimon** [qcz/vscode-text-power-tools#21]
Can I filter on multiple patterns in a file?

I have a large syslog file and I want to be able to filter certain patterns (filter out noise except for the number of patterns I'm interested in).

With grep I would do something like:

```
cat mylog | grep "pat1\|pat2\|pat3"
```

How do I do the same with TPT?

**Comment by qcz** [comment]
You can use the `Filter lines matching a regex (grep)` command and enter `pat1|pat2|pat3` or any other regular expression.

**Comment by BrendanSimon** [comment]
ok thanks.  I was trying `pat1\|pat2\|pat3`.  Great :)
