### ISSUE TITLE
Ctrl + t default key-binding is not working after text-power enabled

### ISSUE THREAD

**Issue by breakersun** [qcz/vscode-text-power-tools#22]
Thank you for such powerful tools, really like it.

I have a little problem: 
- after I enabled this extension, the ctrl + t(default keybinding) is not responded
- when I try "goto symbol in workspace", the function actually works
- when I disabled this extension, the ctrl + t is back

Would you please help me to address this problem?

**Comment by qcz** [comment]
TPT has two keybindings, which are both chords starting with Ctrl + T (`Ctrl+T f`, `Ctrl+T g`). This is why Ctrl+T won't work after installing TPT. As it was an oversight, I will change the default shortcut for these commands in the next release to a shortcut which is not used by default in VS Code. Until then you can remove the keybindings in the keyboard shortcut preferences:

![Code_2021-08-20_09-21-56](https://user-images.githubusercontent.com/304384/130195893-0eeba4de-50c5-4c8b-96d0-d477d7e48fb6.png)

**Comment by breakersun** [comment]
thank you for explaining in detail.
