### ISSUE TITLE
Escape Text for JSON cmd broken

### ISSUE THREAD

**Issue by ImJustStokedToBeHere** [qcz/vscode-text-power-tools#24]
The cmd is properly adding backslash but instead of the length of the string increasing for each char inserted, the string length remains the same, cutting off the end of the escaped string.

 See attached captures for illustration.

Before:
![Capture](https://user-images.githubusercontent.com/46273611/132967652-12f24677-ee21-459b-8f58-df2d4aeb0017.PNG)

After:
![Capture2](https://user-images.githubusercontent.com/46273611/132967653-04cc3aa8-e46c-4a77-b40f-4f34612f37c3.PNG)

**Comment by qcz** [comment]
Fixed in 1.30.0. New version publication started.
