### ISSUE TITLE
[Bug] Functions do nothing if any text is selected

### ISSUE THREAD

**Issue by FireEmerald** [qcz/vscode-text-power-tools#26]
If a user executes any filter command (e.g. _Filter lines including_) **while** something is selected in the current file, the command does **nothing** or produces an empty new file.

This behavior is especially for someone new extreme misleading as the user may think the whole extension does not work (that's what i thought). Is this a limitation by vscode? I don't think so...

**Comment by qcz** [comment]
It is actually not a bug, but an originally intended feature, as this command can work only on the selected lines, not the whole document. But I agree that the current solution is confusing, and even almost working invisibly if I select only a few words. Maybe if there is selected text, but it is fewer than 2 lines, it should show a warning or a question.

**Comment by qcz** [comment]
Added new warnings in 1.31.0.
