### ISSUE TITLE
[Feature request] Pre-enter selected text to filter box

### ISSUE THREAD

**Issue by FireEmerald** [qcz/vscode-text-power-tools#27]
I thought the context menu would work like this:
1. Select a word in the file
2. Right click, open context menu and select filter for lines including
3. Filter popup opens with the selected text already pre-entered to the filter box

Step 3. does not work, the selected text is not pre-entered you have to copy it to the box.

**Comment by qcz** [comment]
The original commands cannot be modified to support this scenario as it would destroy the history feature of the commands (the quick pick provided by VS Code has many limitations).
But I can add new commands for filtering using the selected text.

**Comment by qcz** [comment]
Available in 1.31.0. Use the `Filter lines including the selected text` or `Filter lines not including the selected text` commands.
