### ISSUE TITLE
Do not use Ctrl+K in chorded keybindings

### ISSUE THREAD

**Issue by egrieco** [qcz/vscode-text-power-tools#28]
`textPowerTools.filterLinesIncludingString` is bound to `Ctrl+K` by default.

This conflicts with the standard Unix/macOS "kill to end of line" keybinding. Recommend changing it to something else.

**Comment by qcz** [comment]
Is this keybinding comes from an extension?

I see many chorded keybindings starting with Ctrl+K in the default configuration:
* https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf
* https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

**Comment by qcz** [comment]
Closing because no additional information received.

**Comment by egrieco** [comment]
Whoops, missed your request.

`Ctrl-K` is a standard Bash/readline keybinding for `kill-line`. macOS has carried those unixy bindings over in their text handling system so that they generally work inside any text editing widget.

`kill-line` is a very useful command and is pretty hard-wired into a lot of Unix veterans muscle memory at this point.

Mac keyboard shortcuts - Apple Support
https://support.apple.com/en-us/HT201236#text

Commands For Killing (Bash Reference Manual)
https://www.gnu.org/software/bash/manual/html_node/Commands-For-Killing.html

BASH(1) Manual Page
https://opensource.apple.com/source/bash/bash-44.3/doc/bash.html
