### ISSUE TITLE
Sorting all or selected lines

### ISSUE THREAD

**Issue by alecloudenback** [qcz/vscode-text-power-tools#3]
Feature Request: Sort the selected or all lines in the open editor alphabetically

**Comment by qcz** [comment]
@alecloudenback: VS Code already has this function built in (`Sort Lines Ascending`, `Sort Lines Descending`). It works a little differently as it does not work if nothing is selected (unlike most Text Power Tools commands), however it supports multiple selections.

**Comment by alexolog** [comment]
@qcz  
Does VSCode natively support both case-sensitive and case-insensitive sort?

**Comment by qcz** [comment]
It does not support case sensitive sort AFAIK.

**Comment by alexolog** [comment]
So this feature request is relevant.

**Comment by qcz** [comment]
@alexolog Please make a feature request issue for case sensitive sort if you need that feature.
