### ISSUE TITLE
[bug] For URL Encode new line is not replaced by '%0A'

### ISSUE THREAD

**Issue by cheshi-mantu** [qcz/vscode-text-power-tools#31]
Hi there
thanks a lot for a very useful tool.
There is a bug when you trying to URL encode a text containing several lines like for example
```
line one
line two
```
I'm expecting the URL encode to replace new line character with `%0A` but the result is still 2 lines of text:
```
line%20one
line%20two
```
while proper encoding should be like
```
line%20one%0Aline%20two
```
So, this would be possible: 
```
<a href="mailto:email@email.com?subject=Hello%20there&body=line%20one%0Aline%20two">send email</a>
```

**Comment by qcz** [comment]
Available in 1.31.0.
