### ISSUE TITLE
[Feature] remove ^ before package version

### ISSUE THREAD

**Issue by tjx666** [qcz/vscode-text-power-tools#34]
![image](https://user-images.githubusercontent.com/41773861/150673592-5364e779-6ed1-4db8-a97a-b79fb860c5d1.png)

**Comment by qcz** [comment]
:smile:

Not that I'm not able to do it (after all you can do it pretty easily with basic VS Code editing tools or using some of Text Power Tools own commands), but I'm not 100% sure that that this is the right thing to do. After all there is a lock file for a reason in the repository.

**Comment by qcz** [comment]
@mrienstra 

😄

Not that I'm not able to do it (after all you can do it pretty easily with basic VS Code editing tools or using some of Text Power Tools own commands), but I'm not 100% sure that that this is the right thing to do. After all there is a lock file for a reason in the repository.

**Comment by tjx666** [comment]
My use case is in some package, there some dep is prefix with ^, other are not. So I want to remove all or add all.
As for lock file, people who using this command must will pnpm install after call it.

**Comment by qcz** [comment]
Then I will add `^` to the two packages which do not have it (`prettier` in devDependencies and `html-entities` in dependencies). Cannot add it to faker though as I use a special fork of it.

**Comment by mrienstra** [comment]
> Then I will add `^` to the two packages which do not have it

@qcz, I think there has been a misunderstanding. I believe @tjx666 was proposing a new user-facing feature, which would make it easy to add or remove `^` from all semver ranges in a given file. Though I may be mistaken.

**Comment by tjx666** [comment]
@mrienstra you are right. My meaning is not to modify the extension project lock file. I just want this extension provide a new command to remove all `^` in package.json

**Comment by tjx666** [comment]
Maybe we can just use vscode multi cursor edit feature
