### ISSUE TITLE
\n newline works for one occurence in the output for "Extract information from text into a new editor"

### ISSUE THREAD

**Issue by doubleell** [qcz/vscode-text-power-tools#38]
I had tried the \n character in the 2nd input box for the  "Extract information from text into a new editor" command, however it seems only the first \n is parsed;

2nd input box;
void $1(void) \n { \n } \n

New file output;
void FunctionName(void) 
 { \n } \n

**Comment by qcz** [comment]
Fixed in 1.31.1.
