### ISSUE TITLE
Apply commands to active editor instead of displaying error dialog

### ISSUE THREAD

**Issue by hukacode** [qcz/vscode-text-power-tools#39]
Hello @qcz

The current behavior is we have to select all the texts before running the commands (e.g. Filter lines including a string) or we will get 
"This function does not work without selection." error message.

Could you consider changing the behavior to apply to the current (active) editor?

**Comment by qcz** [comment]
Yep, it was an unintended change in the 1.31.0 release. Works as before in the new 1.31.2 release if nothing is selected.
