### ISSUE TITLE
[Feature Request] Expose all features in a submenu of the right-click context menu in the text editor. 

### ISSUE THREAD

**Issue by visusys** [qcz/vscode-text-power-tools#45]
The command palette is OK, but it would be more convenient to get to the commands if they were added to the right click context menu within a `Text Power Tools` submenu. I am going to write a custom wrapper extension to do this manually, but it would be very nice if this was added out of the box.

Thanks for considering.

**Comment by qcz** [comment]
It already has a Text Power Tools submenu in the editor:

![Code_2022-08-13_12-09-25](https://user-images.githubusercontent.com/304384/184479149-093bb8fb-e01a-4ed2-9af1-375e71871a50.png)

AFAIK all TPT commands are available here.

Is there any particular command that you are missing or you thinking of a different right click context menu?

**Comment by qcz** [comment]
Closing this as this feature is already available for some time and no contradicting info received.
