### ISSUE TITLE
[Feature Request] find duplicate line

### ISSUE THREAD

**Issue by toohandsome** [qcz/vscode-text-power-tools#50]
find duplicate line is a common requirement in my work, I used to sort text first, and then use regular matching to find duplicate lines,this way is too pesky. Is it possible to provide similar functions

**Comment by qcz** [comment]
How would that exactly work? What would be the result of a find duplicate line command?

- There is already a command called `Count line occurrences` (and `Count line occurrences into a new editor` which generates a view that shows a given line how many times shows up in a file.
- There is a `Remove duplicated lines` command which removes all later duplicates of a given line.

**Comment by toohandsome** [comment]
"Count line occurrences into a new editor" solved my question , 3q
