### ISSUE TITLE
[feature request] space separeted text

### ISSUE THREAD

**Issue by bokunodev** [qcz/vscode-text-power-tools#52]
Add variant of snake case, space separeted case.
i migrated ffrom sublime to vscode, i miss this feature from sublime.
its like snake case but separated by space (exactly one space, it remove extra spaces if the selected text contain multiple of any whitespaces) instead of `_`

**Comment by qcz** [comment]
Did you use an extension for that. If so, which one?

**Comment by qcz** [comment]
Available in 1.38.0 as _Separate words with spaces_.
