### ISSUE TITLE
Multi cursor paste by lines

### ISSUE THREAD

**Issue by zardoy** [qcz/vscode-text-power-tools#56]
I feel like this extension should focus on more basic text editing commands :)

Default behavior of vscode is to paste the same text in all cursors if N of cursors doesn't match N of lines in clipboard (as default "editor.multiCursorPaste": "spread")
 BUT I want command that uses the same behavior but for any number of lines in clipboard

 eg I have `1\n2\n3` in clipboard and two cursors I expect `1` and `2` to be pasted

 impl https://github.com/zardoy/extra-commands/blob/8d1702b4ec79c75763ebad1ee6630cf885e5e5f9/src/textCommands/multiCursorPasteByLines.ts

**Comment by qcz** [comment]
> I feel like this extension should focus on more basic text editing commands :)

Feel free to suggest more features to implement.

The requested feature is available via the `Spread paste lines from clipboard` family of commands in 1.39.0.
