### ISSUE TITLE
New Features/Questions

### ISSUE THREAD

**Issue by DarkAoRaidenX** [qcz/vscode-text-power-tools#59]
Yo, sorry not sure how GitHub works and i didn't see an email. 

I am wondering how add/get rid of options I wouldn't use? 

I am trying to find an lowercase option i don't see it and why does CONSTANT CASE have a _ in it. 

Can I have options for both options like CONSTANT CASE and CONSTANT_CASE

For these use cases i have to go back to Notepad++ or other commands/programs for things like that.

**Comment by qcz** [comment]
> I am wondering how add/get rid of options I wouldn't use?

I suppose you mean commands. Currently there is no way to do this. It is maybe possible to assign them to settings, but it is a huge undertaking.

> I am trying to find an lowercase option i don't see it and why does CONSTANT CASE have a _ in it.
> Can I have options for both options like CONSTANT CASE and CONSTANT_CASE

The thing we call CONSTANT_CASE had an _ everywhere where I saw it. What is your use case? Isn't the built in 'Transform to uppercase' command you want?

**Comment by qcz** [comment]
Closing as no answer received.
