### ISSUE TITLE
Really silly question

### ISSUE THREAD

**Issue by phDaveGit** [qcz/vscode-text-power-tools#6]
How do you bring up the search box to search using Text Power Tools in a file in Visual Studio Code?

From the animated gif, I cannot see how this is done.  It appears that you click off screen, to the bottom left and then suddenly the search box appears at the top to allow you to filter text???!!!?!?!

**Comment by qcz** [comment]
The click was used to stop the animated gif recording.

This is how it was done (using only keyboard, no mouse involved):
- Press **Ctrl + P** to open the command palette of VS Code.
- Enter `filterinc`, this filters the list of available commands (you can use `filter`, `filterexc` or anything else, the search is very flexible). If not the command you want is selected, use the arrow key to select the command and press Enter.
- Enter the text you want to filter for or select an item from the history using the arrow keys.

**Comment by phDaveGit** [comment]
Ctrl + P works to bring up the command palette of VS Code, however when I enter "filterinc" I get "No results found"

**Comment by qcz** [comment]
You have to use **Ctrl + Shift + P** instead of Ctrl + P (the latter brings up the list of files instead of the command list of VS Code)
