### ISSUE TITLE
[Feature request] Unescape JSON

### ISSUE THREAD

**Issue by jwikman** [qcz/vscode-text-power-tools#60]
There is already a function for **"Escape text for JSON"**. It converts texts as `"c:\MySample\file.txt"` to `\"c:\\MySample\\file.txt\"`

I would be very happy if the other way around was supported as well, **"Unescape JSON"**. It should do exactly the opposite, so `\"c:\\MySample\\file.txt\"` should become `"c:\MySample\file.txt"`.

**Comment by qcz** [comment]
Available in 1.40.0.

**Comment by jwikman** [comment]
> Available in 1.40.0.

Awesome thanks! It seems to work as expected! :)

BUT, somehow this change messed with the "Escape text for JSON" feature, it now cuts of the last character. I'll create a new issue for that one :)
