### ISSUE TITLE
Generate random decimal from range

### ISSUE THREAD

**Issue by ScarpMetal** [qcz/vscode-text-power-tools#61]
### Description
It would be great if we could generate random numbers from a range (ex: 1000 - 1200, 100 - 1000). I've been using this extension a lot for generating mock data, but the `Generate fake/random data...` > `Random decimal characters` command often isn't sufficient for generating things like random epoch times.

### Possible Flow
1. User opens command pallette and selects `Generate fake/random data...` > `Random decimal characters in range...`
2. A two part text input opens (see `Insert decimal number sequence with custom increments starting at...` command) and prompts the user for the minimum value and the maximum value in the range.
3. Random numbers within that range are generated at each cursor.

### Additional Comments
I figure if someone adds in the decimal version of this, it would also make sense to add in the hex version as well.

**Comment by qcz** [comment]
Available in 1.40.0 (has decimal, hex and real number support).

**Comment by ScarpMetal** [comment]
Dude, you are incredible, this helps so much!
