### ISSUE TITLE
Generate random string from list

### ISSUE THREAD

**Issue by ScarpMetal** [qcz/vscode-text-power-tools#62]
### Description
Generate a string from a list of random strings (ex: red,blue,green). I've been using this extension a lot for generating mock data and this is another command that would be useful to have. A trouble that I've run into recently is quickly generating random US state codes from a list of 3 items.

### Possible Flow
1. User opens command palette and selects `Generate fake/random data...` > `Random string from list...`
2. A text input opens and prompts the user to enter a comma separated list of strings.
3. A random string from the list is selected and returned for each cursor.

**Comment by qcz** [comment]
Available in 1.40.0.

**Comment by ScarpMetal** [comment]
Awesome, thank you so much!
