### ISSUE TITLE
[Bug] "Escape text for JSON" cuts of the last character

### ISSUE THREAD

**Issue by jwikman** [qcz/vscode-text-power-tools#63]
In v1.40.0, the "Escape text for JSON" feature started to cut of the last character of the string being converted.

I just ran the function on a "asfd" string, and it gets shorter and shorter for every execution. :)

**Comment by qcz** [comment]
Thanks for the issue.
Fixed in 1.40.1.

**Comment by jwikman** [comment]
Thanks @qcz, now it seems to work as expected again. 👍
