### ISSUE TITLE
Implement sed one-liner "Join pairs of lines side-by-side"

### ISSUE THREAD

**Issue by GreyArea765** [qcz/vscode-text-power-tools#67]
I'm sure there's an argument for implementing "Join N-numbers of lines side-by-side" but pairs is such a common requirement that I feel it would be useful to many.

It's a sed one-liner:
`sed '$!N;s/\n/ /' input.txt`

Or done via the linux `paste` command:
`paste -s -d' \n' input.txt`

**Comment by qcz** [comment]
Added _Join every two/N lines_ family of commands in 1.41.0.
