### ISSUE TITLE
[Feature Request] Convert JSON to javascript and vice versa

### ISSUE THREAD

**Issue by Zzombiee2361** [qcz/vscode-text-power-tools#71]
I'd like to convert JSON object to javascript object, basically just removing quotes from the key and (optionally) format it. Like this:
<img width="1440" alt="image" src="https://github.com/qcz/vscode-text-power-tools/assets/37852137/1082afd8-54ad-4f9b-ad59-ff8d2ef975e6">

**Comment by qcz** [comment]
It is a very nice feature, but parsing JSON content is outside of the scope a of this plugin.

However you can use ESLint and configure the [quote-props](https://eslint.org/docs/latest/rules/quote-props) rule, which can automatically do this for you on save in VS Code (or when running the eslint fix command).
