### ISSUE TITLE
About translate it into Chinese and generate fake geocoordinates datas

### ISSUE THREAD

**Issue by coloraven** [qcz/vscode-text-power-tools#79]
First of all.
This plugin is really powerful, with many features even more robust than those in VSCode itself. 

However, I hope it can have a Chinese version, including Chinese descriptions of the plugin itself and the generation of random Chinese names and addresses as fake data. I can provide the translated Chinese file, but I don't know how to make the plugin automatically adapt and choose the appropriate language for display.

Additionally, could you add the feature to randomly generate pairs of geocoordinates (longitude is from -180 to 180, and the latitude is from -90 to 90) representing longitude and latitude on Earth?
I was originally planning to use TPT's 'Generate random real numbers from range' func and then merge even and odd lines into one line, but I found that there isn't a feature to merge even and odd lines into one line.
SO.merge even and odd lines into one line is the another additionally feature requests.

Thank you for developing such a powerful and practical plugin.

**Comment by qcz** [comment]
@coloraven You can now translate the extension to Chinese. You have to translate the following two files:
- package.nls.json
- l10n/bundle.l10n.json

Create a copy of them with the appropriate language code for the Chinese dialect of yours (for example the Japanese localization needs a `package.nls.ja.json` and a `l10n/bundle.l10n.ja.json`).

I'll look into expanding the fake name & other generation tools to support more languages.

The random coodinate generator will be in the next version of the extension, thanks for the great idea!

**Comment by qcz** [comment]
Generate random coordinates function is available in 1.46.0.
