### ISSUE TITLE
Added setting options to control the menu context display.

### ISSUE THREAD

**Issue by tiansin** [qcz/vscode-text-power-tools#8]
@qcz  In this way, we can freely control which command menus are displayed, rather than fixed.

**Comment by qcz** [comment]
Not a bad idea. However I'm waiting for the completion of microsoft/vscode#100172, so I can put all possible commands into nice submenus. Let's see how that turns out and if it won't be suitable for what I imagined, I'll implement your idea.

**Comment by qcz** [comment]
The submenu API is available now in VS Code Insiders, so I've experimented with it. All commands are available in the submenus and I think it looks great:

![Code_-_Insiders_2020-07-25_10-06-28](https://user-images.githubusercontent.com/304384/88452459-1d7a7100-ce5f-11ea-922a-bbc95a8fd3a4.png)

**Comment by tjx666** [comment]
Waiting for it, now there is too many menu items in my editor context

**Comment by qcz** [comment]
1.16.0 with the new submenu feature is already published to the VS Code Extension Marketplace. It will be immediately available when VSCode 1.50 releases next week, and it is already available if you use VS Code Insiders.
