### ISSUE TITLE
Wrong selection after inserting number sequence

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [qcz/vscode-text-power-tools#80]
https://github.com/qcz/vscode-text-power-tools/assets/39968/0b07d752-2f15-4ecb-ac66-a22047ab6a10

**Comment by qcz** [comment]
I am not able to reproduce this bug in version 1.87.2, so it was probably a bug in VSCode itself or caused by an other extension.

Please let me know if you still have this problem.

**Comment by qcz** [comment]
No further info received, closing.
