### ISSUE TITLE
[Feature Request] Convert @ to its HTML entity equivalent (&#64;)

### ISSUE THREAD

**Issue by smfukaya** [qcz/vscode-text-power-tools#81]
Angular 17 brought control flow blocks that starts with @ (e.g.: @if, @for). So, in order to print "@" in HTML template, now we have to convert it to its HTML entity equivalent (`&#64;`) or we will get:

`NG5002: Incomplete block "For". If you meant to write the @ character, you should use the "&#64;" HTML entity instead.`

**Comment by qcz** [comment]
Added _Encode HTML entities (all named references)_ command in 1.46.0 which converts `@`, `{` and `}` to its HTML entity versions (not the numeric version, the proper ones, but they works exactly the same).

**Comment by smfukaya** [comment]
It worked like a charm! It replaced `@` with `&commat;` (Commercial At). Thanks very much Dániel Tar!
