### ISSUE TITLE
[Feature request] Convert to titlecase aka capitalcase

### ISSUE THREAD

**Issue by blueray453** [qcz/vscode-text-power-tools#9]
Please add the option to convert text to titlecase (Currently I am using TextTransform).

titlecase means convert each first letter of each word to upper case.

For Example: 

ALGORITHMIC GRAPH THEORY AND PERFECT GRAPHS, 2ND EDITION

Becomes

Algorithmic Graph Theory And Perfect Graphs, 2nd Edition

**Comment by qcz** [comment]
Hello @blueray453! Title case is supported by VS Code by default. This is why I not implemented it in Text Power Tools.
The command is called `Transform to Title Case`.

**Comment by blueray453** [comment]
Thank you very much.
