### ISSUE TITLE
Command labels for "filter lines not including string" incorrect

### ISSUE THREAD

**Issue by dmbaio** [qcz/vscode-text-power-tools#90]
The copy and cut options for filtering lines not including a string mistakenly say, "into a new editor" when they should say, "to clipboard".

Before:
```
Copy lines not including a string into a new editor
Cut lines not including a string into a new editor
```
After:

```
Copy lines not including a string to clipboard
Cut lines not including a string to clipboard
```

**Comment by qcz** [comment]
Do you have this problem with a non-English language? The English version is correct:

![Code_2024-07-18_11-17-21](https://github.com/user-attachments/assets/d061a2d2-c6fa-4090-8d43-a555515b08ac)

![Code_2024-07-18_11-17-29](https://github.com/user-attachments/assets/a2b76bcd-a4fa-4321-8500-ce37f96efaa4)

**Comment by dmbaio** [comment]
No, I mean in English. I do not have the "Copy lines not including a string to clipboard" or "Cut lines not including a string to clipboard" options on any of my machines with this extension.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/4025d5a6-7f21-45d0-88f4-f829e7ca8a3e">
<img width="606" alt="image" src="https://github.com/user-attachments/assets/3f4621c1-3ef1-4c83-9ed7-30477c08194d">
<img width="861" alt="Untitled" src="https://github.com/user-attachments/assets/e2dbdeb8-b7e0-4827-abb2-b72ea44f667d">

**Comment by dmbaio** [comment]
Well, I saw that you just pushed v1.48. I don't even see this in the commit diff, but it is now fixed. ¯\_(ツ)_/¯
