### ISSUE TITLE
bug? case change removes punctuation

### ISSUE THREAD

**Issue by cobblepot1** [qcz/vscode-text-power-tools#94]
I sometimes want to use the Change case functions to modify text strings that includes punctuation. But when I select text and transform to sentence case, all punctuation is removed. I don't see why case change should automatically do this. Any chance the Change case functions can be modified or have an option to not affect punctuation? Thanks.

**Comment by qcz** [comment]
Yeah, I agree: in the case of sentence case it is a bug. Title Case, swap case and sponge case does not remove punctuation. All other change case functions are intended for programmers, and all punctuation should be stripped.

**Comment by qcz** [comment]
Sentence case fixed in 1.50.0.
